#!/bin/sh

# vim-plug
if test ! -f "$HOME/.vim/autoload/plug.vim"
then
  echo "Installing vim-plug for you."
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# zim
if ! [ -f $(which zimfw) ]
then
  echo "Installing Zim for you."
  curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
fi

# homebrew
if test ! $(which brew)
then
  echo "Installing Homebrew for you."
  # Install the correct homebrew for each OS type
  if test "$(uname)" = "Darwin"
  then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  elif test "$(expr substr $(uname -s) 1 5)" = "Linux"
  then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
  fi
fi

# rcm
if test ! $(which rcup)
then
  echo "Installing rcm for you."
  brew install rcm
fi

# exa
if test ! $(which exa)
then
  echo "Installing exa for you."
  brew install exa
fi

# bat
if test ! $(which bat)
then
  echo "Installing bat for you."
  brew install bat
fi

exit 0
