#!/bin/sh

# vim-plug
if test ! -f "$HOME/.vim/autoload/plug.vim"
then
  echo "Installing vim-plug for you."
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# oh-my-zsh
if ! [ -f $(which omz) ]
then
  echo "Installing ohmyzsh for you."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# homebrew
if test ! $(which brew)
then
  echo "Installing Homebrew for you."
  # Install the correct homebrew for each OS type
  if test "$(uname)" = "Darwin"
  then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  elif test "$(expr substr $(uname -s) 1 5)" = "Linux"
  then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
  fi
fi

# rcm
if test ! $(which rcup)
then
  echo "Installing rcm for you."
  brew install rcm
fi

# exa
if test ! $(which exa)
then
  echo "Installing exa for you."
  brew install exa
fi

# bat
if test ! $(which bat)
then
  echo "Installing bat for you."
  brew install bat
fi

if [ -z $(brew list | grep kube-ps1) ]
then
  echo "Installing kube-ps1 for you."
  brew install kube-ps1
fi

if [ -z $(brew list | grep fzf) ]
then
  echo "Installing fzf for you."
  brew install fzf
fi

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

exit 0
