# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jaychung/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jaychung/google-cloud-sdk/path.zsh.inc'; fi

export ZSH="/Users/jaychung/.oh-my-zsh"
export UPDATE_ZSH_DAYS=4
export DOTFILES=$HOME/dotfiles

ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
  zsh-completions
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

if [ -d "$DOTFILES" ];
then
  # all of our zsh files
  typeset -U config_files
  config_files=($DOTFILES/**/*.zsh)

  # load the path files
  for file in ${(M)config_files:#*/path.zsh}
  do
    source $file
  done

  # load everything but the path and completion files
  for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}
  do
    source $file
  done

  # load every completion after autocomplete loads
  for file in ${(M)config_files:#*/completion.zsh}
  do
    source $file
  done

  unset config_files
fi

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jaychung/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jaychung/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jaychung/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jaychung/google-cloud-sdk/completion.zsh.inc'; fi
export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"

export PATH=/Users/jaychung/.tiup/bin:$PATH

# pnpm
export PNPM_HOME="/Users/jaychung/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end
